spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml

#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ilkinsuleymanov200@gmail.com
#    password: ilkin2001 # Use App Password if 2FA is enabled
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
server:
  port: 8080

#  spring:
#    cloud:
#      compatibility-verifier:
#        enabled= true:

feign:
  client:
    config:
      default:
        connectTimeout: 5000  # Connection timeout (in ms)
        readTimeout: 5000     # Read timeout (in ms)


redis:
  server:
    urls: redis://localhost:6379


#  swagger-ui:
#    path: /swagger-ui/index.html
#    enable: true
#  show-actuator: true
#  packages-to-scan: com.example.demo.controller

#logging:
#  level:
#    liquibase: DEBUG  # This enables detailed logging for Liquibase migrations
#    liquibase.sql: TRACE  # Logs the SQL statements generated by Liquibase
#    liquibase.change: DEBUG  # Logs detailed information about changesets applied by Liquibase
#
#    # Optional: You can also set the root logging level to info or debug as per your requirement
#    root:
#      level: INFO
#
#
#springdoc:
#    api-docs:
#      enabled: true
#    swagger-ui:
#      enabled: true

#  15672



